"""initial schema

Revision ID: f6b5c626ff26
Revises: 
Create Date: 2026-07-24 10:07:55.262136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = 'f6b5c626ff26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_sources',
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('package_id', sa.String(length=255), nullable=False),
    sa.Column('play_store_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_sources_package_id'), 'app_sources', ['package_id'], unique=True)
    op.create_table('dictionary_negative',
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionary_negative_word'), 'dictionary_negative', ['word'], unique=True)
    op.create_table('dictionary_positive',
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionary_positive_word'), 'dictionary_positive', ['word'], unique=True)
    op.create_table('normalization_dictionary',
    sa.Column('informal_word', sa.String(length=255), nullable=False),
    sa.Column('formal_word', sa.String(length=255), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalization_dictionary_informal_word'), 'normalization_dictionary', ['informal_word'], unique=True)
    op.create_table('stopwords',
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stopwords_word'), 'stopwords', ['word'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', app.models.types.GUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('datasets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('app_source_id', app.models.types.GUID(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('preprocessing_status', sa.String(length=20), nullable=False),
    sa.Column('labeling_status', sa.String(length=20), nullable=False),
    sa.Column('label_mode', sa.String(length=10), nullable=False),
    sa.Column('training_status', sa.String(length=20), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_source_id'], ['app_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_app_source_id'), 'datasets', ['app_source_id'], unique=False)
    op.create_table('collection_jobs',
    sa.Column('app_source_id', app.models.types.GUID(), nullable=False),
    sa.Column('dataset_id', app.models.types.GUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('max_reviews', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('sort_order', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('found_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by', app.models.types.GUID(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['app_source_id'], ['app_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_jobs_app_source_id'), 'collection_jobs', ['app_source_id'], unique=False)
    op.create_index(op.f('ix_collection_jobs_dataset_id'), 'collection_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_collection_jobs_status'), 'collection_jobs', ['status'], unique=False)
    op.create_table('data_splits',
    sa.Column('dataset_id', app.models.types.GUID(), nullable=False),
    sa.Column('label_mode', sa.String(length=10), nullable=False),
    sa.Column('train_size', sa.Float(), nullable=False),
    sa.Column('test_size', sa.Float(), nullable=False),
    sa.Column('random_state', sa.Integer(), nullable=False),
    sa.Column('stratify', sa.Boolean(), nullable=False),
    sa.Column('train_review_ids', sa.JSON(), nullable=False),
    sa.Column('test_review_ids', sa.JSON(), nullable=False),
    sa.Column('class_distribution', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_splits_dataset_id'), 'data_splits', ['dataset_id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('dataset_id', app.models.types.GUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('validation_report', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by', app.models.types.GUID(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_dataset_id'), 'import_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('dataset_id', app.models.types.GUID(), nullable=False),
    sa.Column('app_source_id', app.models.types.GUID(), nullable=False),
    sa.Column('review_id', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('user_image', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('thumbs_up_count', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('reply_content', sa.Text(), nullable=True),
    sa.Column('reply_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['app_source_id'], ['app_sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_source_id', 'review_id', name='uq_review_app_source_review_id')
    )
    op.create_index(op.f('ix_reviews_app_source_id'), 'reviews', ['app_source_id'], unique=False)
    op.create_index(op.f('ix_reviews_dataset_id'), 'reviews', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_reviews_fingerprint'), 'reviews', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_reviews_review_date'), 'reviews', ['review_date'], unique=False)
    op.create_index(op.f('ix_reviews_review_id'), 'reviews', ['review_id'], unique=False)
    op.create_table('preprocessing_results',
    sa.Column('review_id', app.models.types.GUID(), nullable=False),
    sa.Column('case_folded_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('tokens', sa.JSON(), nullable=False),
    sa.Column('tokens_no_stopword', sa.JSON(), nullable=False),
    sa.Column('stemmed_text', sa.Text(), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preprocessing_results_review_id'), 'preprocessing_results', ['review_id'], unique=True)
    op.create_table('sentiment_labels',
    sa.Column('review_id', app.models.types.GUID(), nullable=False),
    sa.Column('dataset_id', app.models.types.GUID(), nullable=False),
    sa.Column('label_mode', sa.String(length=10), nullable=False),
    sa.Column('positive_score', sa.Float(), nullable=False),
    sa.Column('negative_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('is_excluded_from_training', sa.Boolean(), nullable=False),
    sa.Column('labeled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_labels_dataset_id'), 'sentiment_labels', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_sentiment_labels_label'), 'sentiment_labels', ['label'], unique=False)
    op.create_index(op.f('ix_sentiment_labels_review_id'), 'sentiment_labels', ['review_id'], unique=False)
    op.create_table('training_runs',
    sa.Column('dataset_id', app.models.types.GUID(), nullable=False),
    sa.Column('data_split_id', app.models.types.GUID(), nullable=True),
    sa.Column('label_mode', sa.String(length=10), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('tfidf_config', sa.JSON(), nullable=False),
    sa.Column('knn_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('selection_metric', sa.String(length=30), nullable=False),
    sa.Column('training_time_seconds', sa.Float(), nullable=True),
    sa.Column('prediction_time_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_split_id'], ['data_splits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_runs_dataset_id'), 'training_runs', ['dataset_id'], unique=False)
    op.create_table('evaluation_metrics',
    sa.Column('training_run_id', app.models.types.GUID(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision_macro', sa.Float(), nullable=False),
    sa.Column('recall_macro', sa.Float(), nullable=False),
    sa.Column('f1_macro', sa.Float(), nullable=False),
    sa.Column('precision_weighted', sa.Float(), nullable=False),
    sa.Column('recall_weighted', sa.Float(), nullable=False),
    sa.Column('f1_weighted', sa.Float(), nullable=False),
    sa.Column('support', sa.JSON(), nullable=False),
    sa.Column('confusion_matrix', sa.JSON(), nullable=False),
    sa.Column('classification_report', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_metrics_training_run_id'), 'evaluation_metrics', ['training_run_id'], unique=False)
    op.create_table('knn_models',
    sa.Column('training_run_id', app.models.types.GUID(), nullable=False),
    sa.Column('n_neighbors', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=30), nullable=False),
    sa.Column('algorithm', sa.String(length=20), nullable=False),
    sa.Column('weights', sa.String(length=20), nullable=False),
    sa.Column('leaf_size', sa.Integer(), nullable=False),
    sa.Column('model_file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_run_id')
    )
    op.create_table('predictions',
    sa.Column('training_run_id', app.models.types.GUID(), nullable=False),
    sa.Column('review_id', app.models.types.GUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('actual_label', sa.String(length=10), nullable=True),
    sa.Column('predicted_label', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('k_used', sa.Integer(), nullable=False),
    sa.Column('neighbors', sa.JSON(), nullable=False),
    sa.Column('prediction_time_ms', sa.Float(), nullable=False),
    sa.Column('created_by', app.models.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_training_run_id'), 'predictions', ['training_run_id'], unique=False)
    op.create_table('tfidf_models',
    sa.Column('training_run_id', app.models.types.GUID(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('vocabulary_size', sa.Integer(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('idf_values', sa.JSON(), nullable=False),
    sa.Column('model_file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_run_id')
    )
    op.create_table('training_run_items',
    sa.Column('training_run_id', app.models.types.GUID(), nullable=False),
    sa.Column('k_value', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=30), nullable=False),
    sa.Column('weights', sa.String(length=20), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision_weighted', sa.Float(), nullable=False),
    sa.Column('recall_weighted', sa.Float(), nullable=False),
    sa.Column('f1_weighted', sa.Float(), nullable=False),
    sa.Column('training_time_seconds', sa.Float(), nullable=False),
    sa.Column('prediction_time_seconds', sa.Float(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_run_items_training_run_id'), 'training_run_items', ['training_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_run_items_training_run_id'), table_name='training_run_items')
    op.drop_table('training_run_items')
    op.drop_table('tfidf_models')
    op.drop_index(op.f('ix_predictions_training_run_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('knn_models')
    op.drop_index(op.f('ix_evaluation_metrics_training_run_id'), table_name='evaluation_metrics')
    op.drop_table('evaluation_metrics')
    op.drop_index(op.f('ix_training_runs_dataset_id'), table_name='training_runs')
    op.drop_table('training_runs')
    op.drop_index(op.f('ix_sentiment_labels_review_id'), table_name='sentiment_labels')
    op.drop_index(op.f('ix_sentiment_labels_label'), table_name='sentiment_labels')
    op.drop_index(op.f('ix_sentiment_labels_dataset_id'), table_name='sentiment_labels')
    op.drop_table('sentiment_labels')
    op.drop_index(op.f('ix_preprocessing_results_review_id'), table_name='preprocessing_results')
    op.drop_table('preprocessing_results')
    op.drop_index(op.f('ix_reviews_review_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_review_date'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_fingerprint'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_dataset_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_app_source_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_dataset_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_data_splits_dataset_id'), table_name='data_splits')
    op.drop_table('data_splits')
    op.drop_index(op.f('ix_collection_jobs_status'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_dataset_id'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_app_source_id'), table_name='collection_jobs')
    op.drop_table('collection_jobs')
    op.drop_index(op.f('ix_datasets_app_source_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stopwords_word'), table_name='stopwords')
    op.drop_table('stopwords')
    op.drop_index(op.f('ix_normalization_dictionary_informal_word'), table_name='normalization_dictionary')
    op.drop_table('normalization_dictionary')
    op.drop_index(op.f('ix_dictionary_positive_word'), table_name='dictionary_positive')
    op.drop_table('dictionary_positive')
    op.drop_index(op.f('ix_dictionary_negative_word'), table_name='dictionary_negative')
    op.drop_table('dictionary_negative')
    op.drop_index(op.f('ix_app_sources_package_id'), table_name='app_sources')
    op.drop_table('app_sources')
    # ### end Alembic commands ###
